FROM almalinux:8.10

RUN dnf -y update
RUN dnf -y install unzip

# PHP
RUN mkdir /run/php-fpm
RUN dnf -y install epel-release
RUN dnf -y install https://rpms.remirepo.net/enterprise/remi-release-8.rpm
RUN dnf module enable -y php:remi-8.3
RUN dnf -y install php php-fpm php-mysqlnd

# Composer
COPY --from=composer:2.7.8 /usr/bin/composer /usr/bin/composer

# Node
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
RUN source ~/.bashrc && nvm install 20.17.0

COPY ./laravel /var/www/html/laravel
WORKDIR /var/www/html/laravel

EXPOSE 9000
CMD ["php-fpm", "-F"]