name: "laravel_vue_tutorial"

services:
  nginx:
    container_name: laravel_vue_tutorial_nginx
    image: nginx:1.26
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www/html/laravel
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: laravel_vue_tutorial_php
    build: 
      context: .
      dockerfile: ./docker/php/dockerfile
    volumes:
      - ./laravel:/var/www/html/laravel
      - ./docker/php/www.conf:/etc/php-fpm.d/www.conf
    depends_on:
      - mysql
  
  mysql:
    container_name: laravel_vue_tutorial_mysql
    image: mysql:8.4
    environment:
      - MYSQL_DATABASE=tutorial
      - MYSQL_USER=tutorial
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
  
  pma:
    container_name: laravel_vue_tutorial_pma
    image: phpmyadmin:5.2
    environment:
      - PMA_HOST=laravel_vue_tutorial_mysql
    ports:
      - 8080:80
    depends_on:
      - mysql